jdk:
  - oraclejdk9
language: clojure
script:
- cd ${TRAVIS_BUILD_DIR}/be && lein midje
- cd ${TRAVIS_BUILD_DIR}/square-sizer && lein test
- cd ${TRAVIS_BUILD_DIR}/column-handler && lein midje
- cd ${TRAVIS_BUILD_DIR}/normaliser && lein midje
install: 
- cd ${TRAVIS_BUILD_DIR}/be && lein deps
- cd ${TRAVIS_BUILD_DIR}/square-sizer && lein deps
- cd ${TRAVIS_BUILD_DIR}/column-handler && lein deps
- cd ${TRAVIS_BUILD_DIR}/normaliser && lein deps
